main: com.larko.LCore.Main
name: LCore
api-version: 1.18
version: A1.0
author: Larko
commands:
  sethome:
  delhome:
  home:
  homes:
  claim:
  unclaim:
  claims:
  addtoclaim:
  removefromclaim:
  lcoins:
  transfer:
  setlcoins:
  shop:
  sell:
  safechest: